#!/bin/bash
# dbs: tpchsf1
#      tpchsf1sharded
#
#      tpchsf10
#      tpchsf10sharded
#
#      tpchsf100
#      tpchsf100sharded
# sharded for multi(2) gpus.
docker exec -it $(./container_id) bin/heavysql -p HyperInteractive --db ssbsf100_sharded
